############ SERVERCORP JPEG IMAGES DOWNLOAD  #################

DOWNLOAD_EMAIL = shared_mailbox@mydomain.com
DOWNLOAD_EMAIL_PASS = "xyz123"
JSONOUT_DIR = /Users/saikatbasu/hop/EmailAttachmentDownload/jsonOut
